version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/app/site
      - ./php:/php-app
    ports:
      - "8206:8206"
      - "8216:8216"
      - "8217:8217"
    depends_on:
      - php
    extra_hosts:
      - "parent:host-gateway"
  php:
    build: 
      dockerfile: php.dockerfile
      context: .
    working_dir: /php-app
    ports:
      - "9000:9000"
    volumes:
      - ./php:/php-app