version: '3.8'

services:
  nginx:
    build: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/app/site
    ports:
      - 8206:8206
      - 8216:8216
    extra_hosts:
      - "parent:host-gateway"